apiVersion: v1
kind: ConfigMap
immutable: true
metadata:
  name: {{ .Release.Name }}-config-{{- toYaml .Values.restCounters.config | sha256sum | trunc 8 }}
data:
  config.yaml: |
    {{- with .Values.restCounters.config }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
