{{- if .Values.restCounters.metrics.networkPolicyEnabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-allow-prometheus-metrics-access
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
      {{- range .Values.restCounters.metrics.networkPolicyFrom }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
          path: /metrics
{{- end }}