{{- if not (lookup "v1" "Secret" .Release.Namespace (printf "%s-secret" .Release.Name)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  REST_COUNTERS_TOKEN: {{ default (randAlphaNum 32) .Values.restCounters.apiToken | b64enc | quote }}  # Encode the token
{{- end }}