apiVersion: v1
kind: Service
metadata:
  name: {{ include "rest-counters-express.fullname" $ }}-api
  labels:
    {{- include "rest-counters-express.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rest-counters-express.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rest-counters-express.fullname" $ }}-metrics
  labels:
    {{- include "rest-counters-express.labels" . | nindent 4 }}
spec:
  type: {{ .Values.restCounters.metrics.service.type }}
  selector:
    {{- include "rest-counters-express.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.restCounters.metrics.service.port }}
      targetPort: {{ .Values.restCounters.metrics.service.port }}
      name: http